# Loads environment variables from the .env file
# Example: GOOGLE_API_KEY=your_api_key_here
from dotenv import load_dotenv

# create_agent creates a LangChain agent.
# The agent connects the LLM with the tools that we give it.
from langchain.agents import create_agent

# @tool converts a normal Python function into a tool
# that the LLM/agent is allowed to call.
from langchain.tools import tool

# HumanMessage represents a message sent by the user.
from langchain_core.messages import HumanMessage

# Gemini integration for LangChain.
# This lets us use Google Gemini as the LLM.
from langchain_google_genai import ChatGoogleGenerativeAI


# Load variables from the .env file into the environment.
# ChatGoogleGenerativeAI will use GOOGLE_API_KEY from there.
load_dotenv()


# ---------------------------------------------------------
# 1. CREATE A TOOL
# ---------------------------------------------------------

# @tool tells LangChain:
# "This Python function can be used by the agent as a tool."
@tool
def search(query: str) -> str:
    """
    Search the internet.

    This description is IMPORTANT because the LLM reads it
    to understand what the tool does and when it should use it.

    Args:
        query:
            The search query generated by the LLM.

    Returns:
        The search result.
    """

    # This lets us see in the terminal when the agent calls the tool
    # and what query Gemini generated.
    print(f"Searching for: {query}")

    # IMPORTANT:
    # This is currently a FAKE search result.
    #
    # We are NOT actually searching the internet.
    # Every time the agent calls this tool,
    # it receives exactly this sentence.
    #
    # Later, we can replace this with a real search engine
    # such as Tavily.
    return "Tokyo weather is sunny."


# ---------------------------------------------------------
# 2. CREATE THE LLM
# ---------------------------------------------------------

# Create the Gemini model that will act as the "brain"
# of our agent.
#
# Gemini will:
# - read the user message
# - see the available tools
# - decide whether it needs a tool
# - decide which tool to call
# - generate the tool arguments
# - read the tool result
# - generate the final answer
llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash"  # Use a valid Gemini model available to your API
)


# ---------------------------------------------------------
# 3. DEFINE THE AVAILABLE TOOLS
# ---------------------------------------------------------

# We give the agent a list of tools it is allowed to use.
#
# Right now there is only one tool:
#
#     search
#
# Later this could look like:
#
# tools = [
#     search,
#     calculator,
#     database_tool,
#     send_email
# ]
tools = [search]


# ---------------------------------------------------------
# 4. CREATE THE AGENT
# ---------------------------------------------------------

# create_agent connects:
#
# Gemini + Tools
#
# Conceptually:
#
#              ┌──────────── search() ────────────┐
#              │                                  │
# User ──> Gemini                                │
#              │                                  │
#              └──── Decide whether to use it ───┘
#
#
# Gemini chooses WHEN to use the tool.
# We do not manually write:
#
# if "weather" in message:
#     search(...)
#
# The model makes that decision itself.
agent = create_agent(
    model=llm,
    tools=tools
)


# ---------------------------------------------------------
# 5. RUN THE AGENT
# ---------------------------------------------------------

def main():

    print("Hello from LangChain course 0.2")

    # Send a conversation state to the agent.
    #
    # "messages" is a list because an agent can have
    # multiple messages in its conversation history:
    #
    # HumanMessage
    # AIMessage
    # ToolMessage
    # AIMessage
    # ...
    result = agent.invoke(
        {
            "messages": [
                HumanMessage(
                    content="What is the weather in Tokyo?"
                )
            ]
        }
    )


    # -----------------------------------------------------
    # WHAT HAPPENS INSIDE agent.invoke()?
    # -----------------------------------------------------
    #
    # Step 1:
    #
    # User:
    # "What is the weather in Tokyo?"
    #
    #               ↓
    #
    # Step 2:
    #
    # Gemini receives:
    #
    # - the user question
    # - information about the available search tool
    #
    #               ↓
    #
    # Step 3:
    #
    # Gemini may decide:
    #
    # "This question needs current information,
    #  and I have a search tool available."
    #
    #               ↓
    #
    # Step 4:
    #
    # Gemini generates a structured tool call,
    # conceptually:
    #
    # {
    #     "name": "search",
    #     "arguments": {
    #         "query": "current weather in Tokyo"
    #     }
    # }
    #
    #               ↓
    #
    # Step 5:
    #
    # LangChain executes:
    #
    # search("current weather in Tokyo")
    #
    #               ↓
    #
    # Step 6:
    #
    # Our Python function returns:
    #
    # "Tokyo weather is sunny."
    #
    #               ↓
    #
    # Step 7:
    #
    # LangChain sends that tool result back to Gemini.
    #
    #               ↓
    #
    # Step 8:
    #
    # Gemini uses the result to generate the final answer.
    #
    #
    # The conversation may therefore look like:
    #
    # HumanMessage
    #      ↓
    # AIMessage(tool_call)
    #      ↓
    # ToolMessage
    #      ↓
    # AIMessage(final answer)


    # result["messages"] contains the entire conversation history.
    #
    # [-1] means:
    # "Give me the last message."
    #
    # .content gives us the content of that final message.
    print(result["messages"][-1].content)


# ---------------------------------------------------------
# 6. PYTHON ENTRY POINT
# ---------------------------------------------------------

# This means:
#
# Run main() only when we execute this file directly:
#
# python main2.py
#
# If this file is imported into another Python file,
# main() will NOT automatically run.
if __name__ == "__main__":
    main()