# Import the function used to load variables from the .env file
from dotenv import load_dotenv

# Import LangChain's PromptTemplate class for creating reusable prompts
from langchain_core.prompts import PromptTemplate

# Import the LangChain integration for Groq-hosted models
from langchain_groq import ChatGroq

# Import the LangChain integration for Google's Gemini models
from langchain_google_genai import ChatGoogleGenerativeAI

from langchain_ollama  import ChatOllama


# Read variables from the .env file
# Example: GROQ_API_KEY and GOOGLE_API_KEY
load_dotenv()


# Define the main function of our Python program
def main():

    # Print a simple message when the program starts
    print("Hello from langchain-course!")


    # Store the information that we want the LLM to work with
    information = """
    Elon Musk is a businessman known for Tesla, SpaceX,
    X and other companies.
    """


    # Create the instructions that we want to send to the LLM
    # {information} is a placeholder that will later be replaced
    summary_template = """
    Given the information below about a person:

    {information}

    I want you to create:
    1. A short summary
    2. Two interesting facts about them
    """


    # Convert our string prompt into a LangChain PromptTemplate object
    summary_prompt_template = PromptTemplate(

        # Tell LangChain that this prompt expects
        # one input variable called "information"
        input_variables=["information"],

        # Tell LangChain which prompt template to use
        template=summary_template,
    )


    # Create our first LLM
    # This model will be accessed through Groq
    llm_1 = ChatGroq(

        # Temperature 0 makes the answer more consistent
        # and less random
        temperature=0,

        # Select which model Groq should run
        model="openai/gpt-oss-20b",
    )


    # Create our second LLM
    # This one uses Google's Gemini API
    llm_2 = ChatGoogleGenerativeAI(
    temperature=0,
    model="gemini-3.6-flash"
        )   

    llm_3 = ChatOllama(
        temperature=0,
        model="qwen3:4b"
            )

    # Create a LangChain pipeline:
    #
    # PromptTemplate → Groq LLM
    #
    # The | symbol connects LangChain components together
    chain_1 = summary_prompt_template | llm_1


    # Create another pipeline:
    #
    # PromptTemplate → Gemini LLM
    chain_2 = summary_prompt_template | llm_2


    chain_3 = summary_prompt_template | llm_3


    # RUN chain_1
    #
    # The key "information" matches:
    # input_variables=["information"]
    #
    # The value 'information' is our Python variable
    #.invoke() Run this LangChain component/pipeline once.
    # containing the Elon Musk text
    response_1 = chain_1.invoke(
        {"information": information}
    )


    # Print a title before showing the Groq result
    print("\n--- GROQ ---")


    # response_1 is an AIMessage object
    # .content gives us the actual text generated by the model
    print(response_1.content)


    # RUN chain_2 using the exact same information
    response_2 = chain_2.invoke(
        {"information": information}
    )


    # Print a title before showing the Gemini result
    print("\n--- GEMINI ---")


    # Print only Gemini's generated text
    print(response_2.text)


    # RUN chain_2 using the exact same information
    response_3 = chain_3.invoke(
            {"information": information}
        )
    
    
        # Print a title before showing the Gemini result
    print("\n--- Ollama ---")
    
    
        # Print only Gemini's generated text
    print(response_3.content)
    


# Check whether this Python file is being executed directly
if __name__ == "__main__":

    # If it is being executed directly, run main()
    main()


"""
PromptTemplate       → build reusable prompts
{information}        → dynamic input placeholder
ChatGroq             → Groq LLM integration
ChatGoogle...        → Gemini integration
prompt | llm         → create a chain
.invoke(...)         → execute the chain
response.content     → get model output
.env                 → securely store API keys
"""