# ---------------------------------------------------------
# IMPORTS
# ---------------------------------------------------------

# Loads environment variables from the .env file
# Example:
# OPENAI_API_KEY=...
# TAVILY_API_KEY=...
from dotenv import load_dotenv

# create_agent creates a LangChain agent
# and connects the LLM with the tools we give it.
from langchain.agents import create_agent

# @tool converts a normal Python function into a LangChain tool
# that the LLM can choose to call.
from langchain.tools import tool

# HumanMessage represents the user's message.
from langchain_core.messages import HumanMessage

# OpenAI chat model integration.
from langchain_google_genai import ChatGoogleGenerativeAI

# Tavily is an external search service.
# It can actually search the internet.
from tavily import TavilyClient


# ---------------------------------------------------------
# LOAD ENVIRONMENT VARIABLES
# ---------------------------------------------------------

# Loads API keys from the .env file.
#
# Example .env:
#
# OPENAI_API_KEY=your_openai_key
# TAVILY_API_KEY=your_tavily_key
load_dotenv()


# ---------------------------------------------------------
# CREATE TAVILY CLIENT
# ---------------------------------------------------------

# This creates a connection to Tavily.
#
# TavilyClient will automatically use:
#
# TAVILY_API_KEY
#
# from the environment.
tavily = TavilyClient()


# ---------------------------------------------------------
# CREATE A SEARCH TOOL
# ---------------------------------------------------------

# @tool tells LangChain:
#
# "The agent is allowed to call this Python function."
#
# The LLM will receive:
# - tool name
# - tool description
# - input arguments
#
# and can decide whether to use it.

def search(query: str):
    """
    Search the internet for current or up-to-date information.

    Use this tool when the user asks about:
    - current weather
    - recent news
    - current events
    - information that may have changed recently

    Args:
        query:
            The search query generated by the LLM.

    Returns:
        Search results returned by Tavily.
    """

    # This print lets us see when the agent chooses
    # to call the search tool.
    print(f"Searching for: {query}")

    # IMPORTANT:
    #
    # Unlike our previous fake tool:
    #
    # return "Tokyo weather is sunny."
    #
    # this actually sends the query to Tavily.
    #
    # Tavily then searches the internet and
    # returns real search results.
    return tavily.search(query=query)


# ---------------------------------------------------------
# CREATE THE LLM
# ---------------------------------------------------------

# This is the "brain" of the agent.
#
# The LLM will:
# - read the user's question
# - see available tools
# - decide whether a tool is needed
# - choose a tool
# - generate tool arguments
# - read the tool result
# - produce the final answer
llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash"  # Use a valid Gemini model available to your API
)


# ---------------------------------------------------------
# DEFINE AVAILABLE TOOLS
# ---------------------------------------------------------

# The agent is allowed to use the search tool.
#
# It does NOT mean the tool will always be used.
#
# The LLM decides whether it needs it.
tools = [search]


# ---------------------------------------------------------
# CREATE THE AGENT
# ---------------------------------------------------------

# create_agent connects:
#
# LLM + Tools
#
# Conceptually:
#
# User
#   ↓
# LLM
#   ↓
# "Do I need a tool?"
#
#     No                Yes
#     ↓                  ↓
# Answer            Call search()
#                        ↓
#                     Tavily
#                        ↓
#                    Internet
#                        ↓
#                 Search results
#                        ↓
#                       LLM
#                        ↓
#                  Final answer
agent = create_agent(
    model=llm,
    tools=tools
)


# ---------------------------------------------------------
# MAIN PROGRAM
# ---------------------------------------------------------

def main():

    print("Hello from LangChain course")

    # Send a user message to the agent.
    #
    # "messages" is a list because the agent maintains
    # a conversation history.
    result = agent.invoke(
        {
            "messages": [
                HumanMessage(
                    content="What is the weather in Tokyo right now?"
                )
            ]
        }
    )


    # -----------------------------------------------------
    # WHAT HAPPENS INSIDE agent.invoke()?
    # -----------------------------------------------------
    #
    # 1.
    # User asks:
    #
    # "What is the weather in Tokyo right now?"
    #
    #                  ↓
    #
    # 2.
    # The LLM sees:
    #
    # - the user's question
    # - the search tool
    # - the tool description
    #
    #                  ↓
    #
    # 3.
    # The LLM may decide:
    #
    # "This question requires current information,
    #  so I should use the search tool."
    #
    #                  ↓
    #
    # 4.
    # The LLM generates a tool call, conceptually:
    #
    # {
    #     "name": "search",
    #     "arguments": {
    #         "query": "current weather in Tokyo"
    #     }
    # }
    #
    #                  ↓
    #
    # 5.
    # LangChain executes:
    #
    # search("current weather in Tokyo")
    #
    #                  ↓
    #
    # 6.
    # Inside search():
    #
    # tavily.search(...)
    #
    #                  ↓
    #
    # 7.
    # Tavily searches the internet
    #
    #                  ↓
    #
    # 8.
    # Tavily returns real search results
    #
    #                  ↓
    #
    # 9.
    # LangChain sends those results back to the LLM
    #
    #                  ↓
    #
    # 10.
    # The LLM uses the results to generate
    # the final answer.


    # result["messages"] contains the full agent conversation.
    #
    # [-1] gets the last message.
    #
    # .content gets the text/content of that message.
    print(result["messages"][-1].content)


# ---------------------------------------------------------
# PYTHON ENTRY POINT
# ---------------------------------------------------------

# main() runs only when this file is executed directly.
#
# Example:
#
# python main.py
if __name__ == "__main__":
    main()